### ISSUE TITLE
No clock file for MIB

### ISSUE THREAD

**Issue by DavidCussans** [DUNE-DAQ/timinglibs#97]
No clock file for MIB 

```(dbt) bash-4.4$ dtsbutler -c connections.xml io MIB reset
Created device MIB
2023-Oct-12 11:29:39,609 WARNING [dunedaq::timing::MasterDesign::validate_firmware_version(...) at /tmp/root/spack-stage/spack-stage-timing-NBT23-10-11-42yb276dckukpk3j37ftjadpw32h44h6/spack-src/src/MasterDesign.cpp:131]  Incompatible minor master firmware version; found: 2, required: 1
Design 'kerberos' on board 'mib' on carrier 'trenz-te0712' with frequency 62.5 MHz
Resetting MIB
ERROR ('RuntimeError' exception): ' Clock config file not found for key: mib_5395_kerberos_cdr'

File "/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NBT23-10-11/spack-0.20.0-gcc-12.1.0/spack-0.20.0/opt/spack/linux-scientific7-x86_64/gcc-12.1.0/timing-NBT23-10-11-42yb276dckukpk3j37ftjadpw32h44h6/lib64/python/timing/cli/io.py", line 126, in reset
   lIO.reset(lPLLConfigFilePath)
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NBT23-10-11/spack-0.20.0-gcc-12.1.0/spack-0.20.0/opt/spack/linux-scientific7-x86_64/gcc-12.1.0/timing-NBT23-10-11-42yb276dckukpk3j37ftjadpw32h44h6/bin/dtsbutler", line 98, in <module>
    cli(obj=DTSContext())
  File "/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NFDT23-10-11/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NFDT23-10-11/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NFDT23-10-11/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NFDT23-10-11/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NFDT23-10-11/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NFDT23-10-11/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NFDT23-10-11/.venv/lib/python3.10/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NFDT23-10-11/.venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/cvmfs/dunedaq-development.opensciencegrid.org/nightly/NBT23-10-11/spack-0.20.0-gcc-12.1.0/spack-0.20.0/opt/spack/linux-scientific7-x86_64/gcc-12.1.0/timing-NBT23-10-11-42yb276dckukpk3j37ftjadpw32h44h6/lib64/python/timing/cli/io.py", line 126, in reset
    lIO.reset(lPLLConfigFilePath)
RuntimeError:  Clock config file not found for key: mib_5395_kerberos_cdr

------------------------------------------------------------
(dbt) bash-4.4$```

**Comment by strilov** [comment]
fixed
